//
// Generated file, do not edit! Created by nedtool 4.6 from bitmessage2.msg.
//

#ifndef _BITMESSAGE2_M_H_
#define _BITMESSAGE2_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>bitmessage2.msg:1</tt> by nedtool.
 * <pre>
 * message bittype
 * {
 *     bool bitval;
 * }
 * </pre>
 */
class bittype : public ::cMessage
{
  protected:
    bool bitval_var;

  private:
    void copy(const bittype& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const bittype&);

  public:
    bittype(const char *name=NULL, int kind=0);
    bittype(const bittype& other);
    virtual ~bittype();
    bittype& operator=(const bittype& other);
    virtual bittype *dup() const {return new bittype(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual bool getBitval() const;
    virtual void setBitval(bool bitval);
};

inline void doPacking(cCommBuffer *b, bittype& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, bittype& obj) {obj.parsimUnpack(b);}


#endif // ifndef _BITMESSAGE2_M_H_

