//
// Generated file, do not edit! Created by nedtool 4.6 from bitmessage.msg.
//

#ifndef _BITMESSAGE_M_H_
#define _BITMESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>bitmessage.msg:16</tt> by nedtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * message bitmessage
 * {
 *     bool source;
 * }
 * </pre>
 */
class bitmessage : public ::cMessage
{
  protected:
    bool source_var;

  private:
    void copy(const bitmessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const bitmessage&);

  public:
    bitmessage(const char *name=NULL, int kind=0);
    bitmessage(const bitmessage& other);
    virtual ~bitmessage();
    bitmessage& operator=(const bitmessage& other);
    virtual bitmessage *dup() const {return new bitmessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual bool getSource() const;
    virtual void setSource(bool source);
};

inline void doPacking(cCommBuffer *b, bitmessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, bitmessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef _BITMESSAGE_M_H_

